logging:
  level:
    org.springframework.security: DEBUG

spring:
  sql.init.mode: embedded

  datasource:
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none

  data:
    rest:
      base-path: /api

  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    template:
      default-destination: tacocloud.order.queue
  kafka:
    producer:
      order:
        topic: tacocloud.orders.topic
        "[bootstrap.servers]": localhost:29888
        "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
        "[value.serializer]": com.example.tacocloud.model.serialization.OrderSerializer
        template:
          "[default.topic]": tacocloud.orders.topic
      taco:
        topic: tacocloud.tacos.topic
        "[bootstrap.servers]": localhost:29888
        "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
        "[value.serializer]": com.example.tacocloud.model.serialization.TacoSerializer
        template:
          "[default.topic]": tacocloud.orders.taco

    consumer:
      order:
        topic: tacocloud.orders.topic
        "[bootstrap.servers]": localhost:29888
        "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
        "[value.deserializer]": com.example.tacocloud.model.serialization.OrderDeserializer
        template:
          "[default.topic]": tacocloud.orders.topic
      taco:
        topic: tacocloud.tacos.topic
        "[bootstrap.servers]": localhost:29888
        "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
        "[value.deserializer]": com.example.tacocloud.model.serialization.TacoDeserializer
        template:
          "[default.topic]": tacocloud.tacos.topic
      logEvent:
        topic: tacocloud.logEvent.topic
        "[bootstrap.servers]": localhost:29888
        "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
        "[value.deserializer]": com.example.tacocloud.model.serialization.TacoDeserializer
        template:
          "[default.topic]": tacocloud.logEvent.topic

