logging:
  level:
    org.springframework.security: DEBUG

spring:
  sql.init.mode: embedded

  datasource:
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none

  data:
    rest:
      base-path: /api

  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    template:
      default-destination: tacocloud.order.queue
  kafka:
    producer:
      bootstrap-servers:
      - localhost:29888
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: com.example.tacocloud.model.serialization.OrderSerializer
      template:
        default-topic: tacocloud.orders.topic

    consumer:
      bootstrap-servers:
      - localhost:29888
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: com.example.tacocloud.model.serialization.OrderDeserializer
      template:
        default-topic: tacocloud.orders.topic
